apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: goormthon-6

images:
  - name: mysql
    newTag: lts

patches:
  - target:
      kind: Secret
      name: mysql-secret
    patch: |
      - op: replace
        path: /stringData
        value:
          MYSQL_ROOT_PASSWORD: rootpassword123
          MYSQL_USER: myuser
          MYSQL_PASSWORD: haengbokasio
          MYSQL_DATABASE: haengbokasio